CREATE DATABASE IF NOT EXISTS lead_db;

USE lead_db;

CREATE OR REPLACE TABLE t_lead (
	id VARCHAR(40) NOT NULL,
	created_by VARCHAR(255) NULL DEFAULT NULL,
	created_date DATETIME NULL DEFAULT NULL,
	deleted BOOLEAN NULL DEFAULT NULL,/* BIT(1) */
	last_modified_by VARCHAR(255) NULL DEFAULT NULL,
	last_modified_date DATETIME NULL DEFAULT NULL,
	version INT(11) NULL DEFAULT NULL,
	city VARCHAR(255) NULL DEFAULT NULL,
	country VARCHAR(255) NULL DEFAULT NULL,
	po_box VARCHAR(255) NULL DEFAULT NULL,
	state VARCHAR(255) NULL DEFAULT NULL,
	street VARCHAR(255) NULL DEFAULT NULL,
	zip VARCHAR(255) NULL DEFAULT NULL,
	annual_revenue DOUBLE NULL DEFAULT NULL,
	assigned_team_id VARCHAR(255) NULL DEFAULT NULL,
	assigned_user_id VARCHAR(255) NULL DEFAULT NULL,
	company_name VARCHAR(255) NULL DEFAULT NULL,
	description VARCHAR(255) NULL DEFAULT NULL,
	designation VARCHAR(255) NULL DEFAULT NULL,
	email VARCHAR(255) NULL DEFAULT NULL,
	email_opt_out BOOLEAN NULL DEFAULT NULL,
	facebook VARCHAR(255) NULL DEFAULT NULL,
	fax VARCHAR(255) NULL DEFAULT NULL,
	first_name VARCHAR(255) NULL DEFAULT NULL,
	industry_lov_id VARCHAR(255) NULL DEFAULT NULL,
	last_name VARCHAR(255) NULL DEFAULT NULL,
	leadsource_lov_id VARCHAR(255) NULL DEFAULT NULL,
	leadstatus_lov_id VARCHAR(255) NULL DEFAULT NULL,
	mobile VARCHAR(255) NULL DEFAULT NULL,
	no_of_employees INT(11) NULL DEFAULT NULL,
	phone VARCHAR(255) NULL DEFAULT NULL,
	rating_id VARCHAR(255) NULL DEFAULT NULL,
	salutation_lov_id VARCHAR(255) NULL DEFAULT NULL,
	twitter VARCHAR(255) NULL DEFAULT NULL,
	website VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE t_lead_extension (
	lead_id VARCHAR(40) NOT NULL,
	extensions VARCHAR(255) NULL DEFAULT NULL,
	extensions_key VARCHAR(255) NOT NULL,
	PRIMARY KEY (lead_id, extensions_key),
	CONSTRAINT lead_extension_fk FOREIGN KEY (lead_id) REFERENCES t_lead (id)
);
